const COMMAND_PERMISSION = {
  ANYONE: "ANYONE",
  ADMIN: "ADMIN",
};

const COMMAND_CATEGORY = {
  GENERAL: "GENERAL",
  USER_ADMIN: "USER_ADMIN",
  DUTY_DEFINITION: "DUTY_DEFINITION",
  KITCHEN: "KITCHEN",
  BATHROOM: "BATHROOM",
  ROOM: "ROOM",
  PAYMENT: "PAYMENT",
  DEBUG: "DEBUG",
  ACCOUNTABILITY: "ACCOUNTABILITY",
};

const COMMAND_CATALOG = [
  {
    key: "start",
    command: "/start",
    category: COMMAND_CATEGORY.GENERAL,
    permission: COMMAND_PERMISSION.ANYONE,
    description:
      "Botni ishga tushiradi va kerak bo'lsa guruh hamda adminni bog'laydi.",
    usage: "/start",
  },
  {
    key: "commands",
    command: "/commands",
    category: COMMAND_CATEGORY.GENERAL,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Barcha buyruqlar va ularning tavsiflarini ko'rsatadi.",
    usage: "/commands",
  },
  {
    key: "help",
    command: "/help",
    aliases: ["/commands"],
    category: COMMAND_CATEGORY.GENERAL,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "/commands buyrug'ining sinonimi.",
    usage: "/help",
  },
  {
    key: "status",
    command: "/status",
    category: COMMAND_CATEGORY.GENERAL,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Botning umumiy holati va faol navbatchiliklarni ko'rsatadi.",
    usage: "/status",
  },

  {
    key: "adduser",
    command: "/adduser",
    category: COMMAND_CATEGORY.USER_ADMIN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchini qo'shadi yoki ro'yxatdan o'tkazadi.",
    usage: "/adduser",
  },
  {
    key: "removeuser",
    command: "/removeuser",
    category: COMMAND_CATEGORY.USER_ADMIN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Telegram user id orqali foydalanuvchini o'chiradi.",
    usage: "/removeuser <telegramUserId>",
  },
  {
    key: "admins",
    command: "/admins",
    category: COMMAND_CATEGORY.USER_ADMIN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Adminlar ro'yxatini ko'rsatadi.",
    usage: "/admins",
  },
  {
    key: "addadmin",
    command: "/addadmin",
    category: COMMAND_CATEGORY.USER_ADMIN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Telegram user id orqali admin qo'shadi.",
    usage: "/addadmin <telegramUserId>",
  },
  {
    key: "removeadmin",
    command: "/removeadmin",
    category: COMMAND_CATEGORY.USER_ADMIN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Telegram user id orqali adminni olib tashlaydi.",
    usage: "/removeadmin <telegramUserId>",
  },
  {
    key: "users",
    command: "/users",
    category: COMMAND_CATEGORY.USER_ADMIN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchilar ro'yxatini ko'rsatadi.",
    usage: "/users",
  },

  {
    key: "duties",
    command: "/duties",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Barcha navbatchilik turlarini ko'rsatadi.",
    usage: "/duties",
  },
  {
    key: "dutyshow",
    command: "/dutyshow",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Kod bo'yicha navbatchilik tafsilotlarini ko'rsatadi.",
    usage: "/dutyshow <code>",
  },
  {
    key: "dutycreate",
    command: "/dutycreate",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Yangi navbatchilik turini yaratadi.",
    usage: "/dutycreate ...",
  },
  {
    key: "dutyenable",
    command: "/dutyenable",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Kod bo'yicha navbatchilikni yoqadi.",
    usage: "/dutyenable <code>",
  },
  {
    key: "dutydisable",
    command: "/dutydisable",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Kod bo'yicha navbatchilikni o'chiradi.",
    usage: "/dutydisable <code>",
  },
  {
    key: "dutysetinterval",
    command: "/dutysetinterval",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Navbatchilik aylanish oralig'ini yangilaydi.",
    usage: "/dutysetinterval <code> <hours|days>",
  },
  {
    key: "dutysetpoll",
    command: "/dutysetpoll",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description:
      "Navbatchilik uchun poll boshlanish va davomiylik vaqtini yangilaydi.",
    usage: "/dutysetpoll <code> <leadHours> <durationMinutes>",
  },
  {
    key: "dutysetcron",
    command: "/dutysetcron",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description:
      "Eslatma asosidagi navbatchiliklar uchun cron jadvalini o'rnatadi.",
    usage: "/dutysetcron <code> <cron>",
  },
  {
    key: "add-task",
    command: "/add-task",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Navbatchilik turiga vazifa qo'shadi.",
    usage: '/add-task "<taskText>" <dutyTypeEnum>',
  },
  {
    key: "remove-task",
    command: "/remove-task",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Navbatchilik turidan vazifani o'chiradi.",
    usage: "/remove-task <taskId> <dutyTypeEnum>",
  },
  {
    key: "tasks",
    command: "/tasks",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Navbatchilik turi bo'yicha vazifalar ro'yxatini ko'rsatadi.",
    usage: "/tasks <dutyTypeEnum>",
  },
  {
    key: "clear-tasks",
    command: "/clear-tasks",
    category: COMMAND_CATEGORY.DUTY_DEFINITION,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Navbatchilik turi uchun barcha vazifalarni o'chiradi.",
    usage: "/clear-tasks <dutyTypeEnum>",
  },

  {
    key: "kitchen",
    command: "/kitchen",
    category: COMMAND_CATEGORY.KITCHEN,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Hozirgi oshxona navbatchisini ko'rsatadi.",
    usage: "/kitchen",
  },
  {
    key: "kitchenlist",
    command: "/kitchenlist",
    category: COMMAND_CATEGORY.KITCHEN,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Oshxona navbati ro'yxatini ko'rsatadi.",
    usage: "/kitchenlist",
  },
  {
    key: "kitchenadd",
    command: "/kitchenadd",
    category: COMMAND_CATEGORY.KITCHEN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchini oshxona navbatiga qo'shadi.",
    usage: "/kitchenadd <userId>",
  },
  {
    key: "kitchenremove",
    command: "/kitchenremove",
    category: COMMAND_CATEGORY.KITCHEN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchini oshxona navbatidan o'chiradi.",
    usage: "/kitchenremove <userId>",
  },
  {
    key: "kitchenskip",
    command: "/kitchenskip",
    category: COMMAND_CATEGORY.KITCHEN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Oshxona navbatchiligini keyingi odamga o'tkazadi.",
    usage: "/kitchenskip",
  },
  {
    key: "kitchenswap",
    command: "/kitchenswap",
    category: COMMAND_CATEGORY.KITCHEN,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Hozirgi va keyingi oshxona navbatchisini almashtiradi.",
    usage: "/kitchenswap",
  },

  {
    key: "bathroom",
    command: "/bathroom",
    category: COMMAND_CATEGORY.BATHROOM,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Hozirgi hammom navbatchi juftligini ko'rsatadi.",
    usage: "/bathroom",
  },
  {
    key: "bathroomlist",
    command: "/bathroomlist",
    category: COMMAND_CATEGORY.BATHROOM,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Hammom navbati yoki juftliklar ro'yxatini ko'rsatadi.",
    usage: "/bathroomlist",
  },
  {
    key: "bathroomadd",
    command: "/bathroomadd",
    category: COMMAND_CATEGORY.BATHROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchini hammom navbatchilari ro'yxatiga qo'shadi.",
    usage: "/bathroomadd <userId>",
  },
  {
    key: "bathroomremove",
    command: "/bathroomremove",
    category: COMMAND_CATEGORY.BATHROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchini hammom navbatchilari ro'yxatidan o'chiradi.",
    usage: "/bathroomremove <userId>",
  },
  {
    key: "bathroompair",
    command: "/bathroompair",
    category: COMMAND_CATEGORY.BATHROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Hammom uchun aniq juftlik yaratadi yoki yangilaydi.",
    usage: "/bathroompair <userId1> <userId2>",
  },
  {
    key: "bathroomskip",
    command: "/bathroomskip",
    category: COMMAND_CATEGORY.BATHROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Hammom navbatchiligini keyingi juftlikka o'tkazadi.",
    usage: "/bathroomskip",
  },

  {
    key: "rooms",
    command: "/rooms",
    category: COMMAND_CATEGORY.ROOM,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Xonalar va ularning egalari ro'yxatini ko'rsatadi.",
    usage: "/rooms",
  },
  {
    key: "roomshow",
    command: "/roomshow",
    category: COMMAND_CATEGORY.ROOM,
    permission: COMMAND_PERMISSION.ANYONE,
    description: "Kod bo'yicha bitta xonani ko'rsatadi.",
    usage: "/roomshow <roomCode>",
  },
  {
    key: "roomcreate",
    command: "/roomcreate",
    category: COMMAND_CATEGORY.ROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Yangi xona yaratadi.",
    usage: "/roomcreate <roomCode> <name>",
  },
  {
    key: "roomdelete",
    command: "/roomdelete",
    category: COMMAND_CATEGORY.ROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Xonani o'chiradi yoki faol emas holatga o'tkazadi.",
    usage: "/roomdelete <roomCode>",
  },
  {
    key: "put",
    command: "/put",
    category: COMMAND_CATEGORY.ROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchini xonaga biriktiradi yoki ko'chiradi.",
    usage: "/put <userId> <roomCode>",
  },
  {
    key: "roomremove",
    command: "/roomremove",
    category: COMMAND_CATEGORY.ROOM,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Foydalanuvchini xonadan olib tashlaydi.",
    usage: "/roomremove <userId>",
  },

  {
    key: "payment",
    command: "/payment",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Joriy to'lov sozlamalarini ko'rsatadi.",
    usage: "/payment",
  },
  {
    key: "payment-per",
    command: "/payment-per",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Joriy oy uchun har bir odam to'laydigan summani belgilaydi.",
    usage: "/payment-per <amount> [currency]",
  },
  {
    key: "payment-amount",
    command: "/payment-amount",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "15-kundagi yig'im uchun amaldagi summani ko'rsatadi.",
    usage: "/payment-amount",
  },
  {
    key: "payment-history",
    command: "/payment-history",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Oxirgi oylardagi to'lov summalari tarixini ko'rsatadi.",
    usage: "/payment-history [months]",
  },
  {
    key: "paymentcard",
    command: "/paymentcard",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Karta orqali to'lov ma'lumotlarini yangilaydi.",
    usage: "/paymentcard <cardNumber> [holderName]",
  },
  {
    key: "paymentcash",
    command: "/paymentcash",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Naqd to'lov bo'yicha ko'rsatmani yangilaydi.",
    usage: "/paymentcash <instruction>",
  },
  {
    key: "paymentmode",
    command: "/paymentmode",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "To'lov usulini o'zgartiradi.",
    usage: "/paymentmode <CARD|CASH|CARD_OR_CASH>",
  },
  {
    key: "paymentday",
    command: "/paymentday",
    category: COMMAND_CATEGORY.PAYMENT,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "To'lov eslatmasi va yig'im kunlarini yangilaydi.",
    usage: "/paymentday <reminderDay> <collectionDay>",
  },

  {
    key: "forcerotate",
    command: "/forcerotate",
    category: COMMAND_CATEGORY.DEBUG,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Kod bo'yicha navbatchilikni majburan aylantiradi.",
    usage: "/forcerotate <dutyCode>",
  },
  {
    key: "forcepoll",
    command: "/forcepoll",
    category: COMMAND_CATEGORY.DEBUG,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Navbatchilik pollini darhol yaratadi.",
    usage: "/forcepoll <dutyCode>",
  },
  {
    key: "resolvepoll",
    command: "/resolvepoll",
    category: COMMAND_CATEGORY.DEBUG,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Joriy navbatchilik pollini qo'lda yakunlaydi.",
    usage: "/resolvepoll <dutyCode>",
  },
  {
    key: "reload",
    command: "/reload",
    category: COMMAND_CATEGORY.DEBUG,
    permission: COMMAND_PERMISSION.ADMIN,
    description: "Konfiguratsiya yoki keshlangan holatni qayta yuklaydi.",
    usage: "/reload",
  },

  {
    key: "badDuties",
    command: "/badDuties",
    category: COMMAND_CATEGORY.ACCOUNTABILITY,
    permission: COMMAND_PERMISSION.ADMIN,
    description:
      "Joriy yoki tanlangan oy uchun badDuty soni chegaradan yuqori foydalanuvchilarni ko'rsatadi.",
    usage: "/badDuties [YYYY-MM]",
  },
];

function findCommandMetadata(command) {
  return COMMAND_CATALOG.find((item) => item.command === command) || null;
}

function listCommandsByCategory(category) {
  return COMMAND_CATALOG.filter((item) => item.category === category);
}

module.exports = {
  COMMAND_PERMISSION,
  COMMAND_CATEGORY,
  COMMAND_CATALOG,
  findCommandMetadata,
  listCommandsByCategory,
};
